### ISSUE TITLE
Add documentation to GutHub Pages

### ISSUE THREAD

**Issue by amc-corey-cox** [bfurner/bdchm#1]
We'd like to have the documentation live from the GitGub pages. I think we can do this easily using the infrastructure we get form cookie-cutter.

**Comment by amc-corey-cox** [comment]
Anne Thessen and Stephanie Hong asked to be involved in this deployment.

**Comment by bfurner** [comment]
1. i updated the .gitignore from the cookiecutter to include /docs in the repo, and checked that in
2. i enabled pages in the repo and pointed it to build and serve from /docs
3. we now have docs here: [https://bfurner.github.io/bdchm/](https://bfurner.github.io/bdchm/) but they are not styled using mkdocs do they are unsightly and not terribly functional.  will need to figure out how to get build in GH to make using the mkdocs config.

**Comment by amc-corey-cox** [comment]
This looks great Brian, nice work!
